# Generated by Django 3.1.7 on 2021-04-02 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves_request',
            old_name='note_area',
            new_name='admin_note_area',
        ),
        migrations.AddField(
            model_name='leaves_request',
            name='staff_note_area',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
