# Generated by Django 3.1.7 on 2021-03-23 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookHolidays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='accounts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidays_request',
            name='Department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='holidays_request',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='holidays_request',
            name='Last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='holidays_request',
            name='Staff_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_level',
            field=models.CharField(max_length=100),
        ),
    ]
