# Generated by Django 3.1.7 on 2021-03-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookHolidays', '0003_auto_20210323_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='accounts',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account'),
            preserve_default=False,
        ),
    ]
