# Generated by Django 3.1.7 on 2021-03-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookHolidays', '0004_staff_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='accounts',
        ),
    ]
