# Generated by Django 3.1.7 on 2021-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookHolidays', '0005_remove_staff_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays_request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
