# Generated by Django 3.1.7 on 2021-04-19 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookHolidays', '0006_holidays_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays_request',
            name='admin_note_area',
            field=models.TextField(default=datetime.date(2021, 4, 19), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidays_request',
            name='staff_note_area',
            field=models.TextField(default=datetime.date(2021, 4, 19), max_length=200),
            preserve_default=False,
        ),
    ]
